package me.brody.mazesurvival.loot;

import me.brody.mazesurvival.Main;
import me.brody.mazesurvival.enchantment.MazeEnchantment;
import me.brody.mazesurvival.item.CustomItem;
import me.brody.mazesurvival.item.ItemGrade;
import me.brody.mazesurvival.utils.ItemGradeUtils;
import me.brody.mazesurvival.utils.WeightedList;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.block.Beehive;
import org.bukkit.entity.Bee;
import org.bukkit.entity.EntityType;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.BlockStateMeta;

import java.util.HashMap;
import java.util.Map;

public class LootTable extends WeightedList<LootTableEntry> {
	public static LootTable STRONGHOLD_LOOT_TABLE;
	public static LootTable DESERT_LOOT_TABLE;
	public static LootTable SWAMP_LOOT_TABLE;
	public static LootTable NETHER_LOOT_TABLE;
	public static LootTable DEEP_DARK_LOOT_TABLE;

	private LootTable() {}

	public static void init(Main plugin) {
		STRONGHOLD_LOOT_TABLE = new LootTable();
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.OAK_LOG)), 4);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.COBBLESTONE)), 2);
		ItemStack cobblestoneIronGrade = new ItemStack(Material.COBBLESTONE);
		ItemGradeUtils.setItemGrade(cobblestoneIronGrade, ItemGrade.IRON);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(cobblestoneIronGrade), 5);
		ItemStack cobblestoneGoldGrade = new ItemStack(Material.COBBLESTONE);
		ItemGradeUtils.setItemGrade(cobblestoneGoldGrade, ItemGrade.GOLD);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(cobblestoneGoldGrade), 5);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.LEATHER)), 3);
		ItemStack leatherIronGrade = new ItemStack(Material.LEATHER);
		ItemGradeUtils.setItemGrade(leatherIronGrade, ItemGrade.IRON);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(leatherIronGrade), 1);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.AMETHYST_SHARD)), 4);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SWIFTNESS.getItemStack()), 3);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SWIFTNESS_EXTENDED.getItemStack()), 5);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SWIFTNESS_II.getItemStack()), 3);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.APPLE)), 3);
		ItemStack appleIronGrade = new ItemStack(Material.APPLE);
		ItemGradeUtils.setItemGrade(appleIronGrade, ItemGrade.IRON);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(appleIronGrade), 3);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.WHEAT_SEEDS)), 2);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.CARROT)), 3);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.DIRT)), 3);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.SAND)), 3);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.GRAVEL)), 3);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.ANDESITE)), 3);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.DIORITE)), 5);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.GRANITE)), 3);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.CHARCOAL)), 5);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.BONE)), 5);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.GOLDEN_APPLE)), 3);
		STRONGHOLD_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.MAZE_RUNNER_BOOTS.getItemStack()), 3);

		Map<MazeEnchantment, Integer> desertEnchantments = new HashMap<>();
		desertEnchantments.put(MazeEnchantment.PROTECTION, 1);
		desertEnchantments.put(MazeEnchantment.THORNS, 1);
		desertEnchantments.put(MazeEnchantment.SOUL_SPEED, 1);
		desertEnchantments.put(MazeEnchantment.VITALITY, 1);
		desertEnchantments.put(MazeEnchantment.SHARPNESS, 1);
		desertEnchantments.put(MazeEnchantment.SMITE, 1);
		desertEnchantments.put(MazeEnchantment.BANE_OF_ARTHROPODS, 1);
		desertEnchantments.put(MazeEnchantment.FIRE_ASPECT, 1);
		desertEnchantments.put(MazeEnchantment.KNOCKBACK, 1);
		desertEnchantments.put(MazeEnchantment.LOOTING, 1);
		desertEnchantments.put(MazeEnchantment.CRUSADER, 1);
		desertEnchantments.put(MazeEnchantment.POWER, 1);
		desertEnchantments.put(MazeEnchantment.PUNCH, 1);
		desertEnchantments.put(MazeEnchantment.LINGERING_SHOT, 1);
		desertEnchantments.put(MazeEnchantment.UNBREAKING, 1);
		DESERT_LOOT_TABLE = new LootTable();
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.RAW_COPPER)), 5);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.TIN.getItemStack()), 5);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.LAPIS_LAZULI)), 5);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SCRIPTING_PAPER.getItemStack()), 5);
		DESERT_LOOT_TABLE.add(new EnchantedScriptLootTableEntry(desertEnchantments, false), 1);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SWIFTNESS_II.getItemStack()), 5);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SWIFTNESS_II_EXTENDED.getItemStack()), 5);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.BIRCH_LOG)), 5);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.BIRCH_SAPLING)), 5);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.POTATO)), 5);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.CACTUS)), 5);
		ItemStack cactusIronGrade = new ItemStack(Material.CACTUS);
		ItemGradeUtils.setItemGrade(cactusIronGrade, ItemGrade.IRON);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(cactusIronGrade), 3);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.SUGAR_CANE)), 5);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.SUGAR)), 5);
		ItemStack sugarIronGrade = new ItemStack(Material.SUGAR);
		ItemGradeUtils.setItemGrade(sugarIronGrade, ItemGrade.IRON);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(sugarIronGrade), 3);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.SAND)), 5);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.RED_SAND)), 5);
		ItemStack redSandIronGrade = new ItemStack(Material.RED_SAND);
		ItemGradeUtils.setItemGrade(redSandIronGrade, ItemGrade.IRON);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(redSandIronGrade), 3);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.SANDSTONE)), 5);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.RED_SANDSTONE)), 5);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.DEAD_BUSH)), 5);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.BONE)), 5);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.GOLDEN_APPLE)), 3);
		DESERT_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.MAZE_RUNNER_BOOTS.getItemStack()), 3);

		Map<MazeEnchantment, Integer> swampEnchantments = new HashMap<>();
		swampEnchantments.put(MazeEnchantment.PROTECTION, 2);
		swampEnchantments.put(MazeEnchantment.THORNS, 2);
		swampEnchantments.put(MazeEnchantment.SOUL_SPEED, 1);
		swampEnchantments.put(MazeEnchantment.VITALITY, 1);
		swampEnchantments.put(MazeEnchantment.SHARPNESS, 1);
		swampEnchantments.put(MazeEnchantment.SMITE, 2);
		swampEnchantments.put(MazeEnchantment.BANE_OF_ARTHROPODS, 2);
		swampEnchantments.put(MazeEnchantment.FIRE_ASPECT, 1);
		swampEnchantments.put(MazeEnchantment.KNOCKBACK, 2);
		swampEnchantments.put(MazeEnchantment.LOOTING, 1);
		swampEnchantments.put(MazeEnchantment.CRUSADER, 2);
		swampEnchantments.put(MazeEnchantment.POWER, 1);
		swampEnchantments.put(MazeEnchantment.PUNCH, 1);
		swampEnchantments.put(MazeEnchantment.LINGERING_SHOT, 1);
		swampEnchantments.put(MazeEnchantment.UNBREAKING, 1);
		SWAMP_LOOT_TABLE = new LootTable();
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.RAW_IRON)), 5);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.LAPIS_LAZULI)), 5);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.ORICHALCUM.getItemStack()), 5);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SCRIPTING_PAPER.getItemStack()), 5);
		SWAMP_LOOT_TABLE.add(new EnchantedScriptLootTableEntry(swampEnchantments, false), 1);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SWIFTNESS_II.getItemStack()), 5);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SWIFTNESS_II_EXTENDED.getItemStack()), 5);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.SPRUCE_LOG)), 5);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.SPRUCE_SAPLING)), 5);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.BEETROOT)), 5);
		ItemStack beetrootIronGrade = new ItemStack(Material.BEETROOT);
		ItemGradeUtils.setItemGrade(beetrootIronGrade, ItemGrade.IRON);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(beetrootIronGrade), 3);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.BROWN_MUSHROOM)), 5);
		ItemStack brownMushroomIronGrade = new ItemStack(Material.BROWN_MUSHROOM);
		ItemGradeUtils.setItemGrade(brownMushroomIronGrade, ItemGrade.IRON);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(brownMushroomIronGrade), 3);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.RED_MUSHROOM)), 5);
		ItemStack redMushroomIronGrade = new ItemStack(Material.RED_MUSHROOM);
		ItemGradeUtils.setItemGrade(redMushroomIronGrade, ItemGrade.IRON);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(redMushroomIronGrade), 3);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.HONEYCOMB)), 5);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.LILAC)), 5);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.ROSE_BUSH)), 5);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.MUD)), 5);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.LILY_PAD)), 5);
		ItemStack beeNestItem = new ItemStack(Material.BEE_NEST);
		BlockStateMeta beeNestMeta = (BlockStateMeta)beeNestItem.getItemMeta();
		Beehive beehive = (Beehive)beeNestMeta.getBlockState();
		for(int i = 0; i < 2; i++) {
			Bee bee = (Bee) plugin.getServer().getWorlds().get(0).spawnEntity(new Location(plugin.getServer().getWorlds().get(0), 0, 0, 0), EntityType.BEE);
			beehive.addEntity(bee);
		}
		beeNestMeta.setBlockState(beehive);
		beeNestItem.setItemMeta(beeNestMeta);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(beeNestItem), 5);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.BONE)), 5);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.GOLDEN_APPLE)), 3);
		SWAMP_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.MAZE_RUNNER_BOOTS.getItemStack()), 3);

		Map<MazeEnchantment, Integer> netherEnchantments = new HashMap<>();
		netherEnchantments.put(MazeEnchantment.PROTECTION, 2);
		netherEnchantments.put(MazeEnchantment.THORNS, 2);
		netherEnchantments.put(MazeEnchantment.SOUL_SPEED, 2);
		netherEnchantments.put(MazeEnchantment.VITALITY, 2);
		netherEnchantments.put(MazeEnchantment.SHARPNESS, 2);
		netherEnchantments.put(MazeEnchantment.SMITE, 4);
		netherEnchantments.put(MazeEnchantment.BANE_OF_ARTHROPODS, 4);
		netherEnchantments.put(MazeEnchantment.FIRE_ASPECT, 2);
		netherEnchantments.put(MazeEnchantment.KNOCKBACK, 2);
		netherEnchantments.put(MazeEnchantment.LOOTING, 2);
		netherEnchantments.put(MazeEnchantment.CRUSADER, 2);
		netherEnchantments.put(MazeEnchantment.POWER, 2);
		netherEnchantments.put(MazeEnchantment.PUNCH, 2);
		netherEnchantments.put(MazeEnchantment.LINGERING_SHOT, 2);
		netherEnchantments.put(MazeEnchantment.UNBREAKING, 2);
		NETHER_LOOT_TABLE = new LootTable();
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SUN_GOLD_NUGGET.getItemStack()), 5);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.TIN.getItemStack()), 5);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.RAW_COPPER)), 5);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.QUARTZ)), 5);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.MITHRIL.getItemStack()), 5);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SCRIPTING_PAPER.getItemStack()), 5);
		NETHER_LOOT_TABLE.add(new EnchantedScriptLootTableEntry(netherEnchantments, false), 1);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SCRIPTING_TOME.getItemStack()), 5);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SWIFTNESS_II_EXTENDED.getItemStack()), 5);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SWIFTNESS_III.getItemStack()), 5);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.NETHER_WART)), 5);
		ItemStack netherWartIronGrade = new ItemStack(Material.NETHER_WART);
		ItemGradeUtils.setItemGrade(netherWartIronGrade, ItemGrade.IRON);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(netherWartIronGrade), 3);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.GHAST_TEAR)), 5);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.NETHERRACK)), 5);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.NETHER_BRICKS)), 5);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.CRIMSON_NYLIUM)), 5);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.WARPED_NYLIUM)), 5);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.SOUL_SAND)), 5);
		ItemStack soulSandIronGrade = new ItemStack(Material.SOUL_SAND);
		ItemGradeUtils.setItemGrade(soulSandIronGrade, ItemGrade.IRON);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(soulSandIronGrade), 3);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.SOUL_SOIL)), 5);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.GRAVEL)), 5);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.BASALT)), 5);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.GLOWSTONE_DUST)), 5);
		ItemStack glowstoneDustIronGrade = new ItemStack(Material.GLOWSTONE_DUST);
		ItemGradeUtils.setItemGrade(glowstoneDustIronGrade, ItemGrade.IRON);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(glowstoneDustIronGrade), 3);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.BONE)), 5);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.GOLDEN_APPLE)), 3);
		NETHER_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.MAZE_RUNNER_BOOTS.getItemStack()), 3);

		Map<MazeEnchantment, Integer> deepDarkEnchantments = new HashMap<>();
		deepDarkEnchantments.put(MazeEnchantment.PROTECTION, 3);
		deepDarkEnchantments.put(MazeEnchantment.THORNS, 3);
		deepDarkEnchantments.put(MazeEnchantment.SOUL_SPEED, 3);
		deepDarkEnchantments.put(MazeEnchantment.VITALITY, 3);
		deepDarkEnchantments.put(MazeEnchantment.SHARPNESS, 3);
		deepDarkEnchantments.put(MazeEnchantment.SMITE, 5);
		deepDarkEnchantments.put(MazeEnchantment.BANE_OF_ARTHROPODS, 5);
		deepDarkEnchantments.put(MazeEnchantment.FIRE_ASPECT, 2);
		deepDarkEnchantments.put(MazeEnchantment.KNOCKBACK, 3);
		deepDarkEnchantments.put(MazeEnchantment.LOOTING, 3);
		deepDarkEnchantments.put(MazeEnchantment.CRUSADER, 3);
		deepDarkEnchantments.put(MazeEnchantment.POWER, 3);
		deepDarkEnchantments.put(MazeEnchantment.PUNCH, 3);
		deepDarkEnchantments.put(MazeEnchantment.LINGERING_SHOT, 3);
		deepDarkEnchantments.put(MazeEnchantment.UNBREAKING, 3);
		DEEP_DARK_LOOT_TABLE = new LootTable();
		DEEP_DARK_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.DIAMOND)), 5);
		DEEP_DARK_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.ADAMANTITE_INGOT.getItemStack()), 5);
		DEEP_DARK_LOOT_TABLE.add(new EnchantedScriptLootTableEntry(deepDarkEnchantments, true), 1);
		DEEP_DARK_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SCRIPTING_TOME.getItemStack()), 5);
		DEEP_DARK_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SWIFTNESS_II_EXTENDED.getItemStack()), 5);
		DEEP_DARK_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SWIFTNESS_III.getItemStack()), 5);
		DEEP_DARK_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.SWIFTNESS_III_EXTENDED.getItemStack()), 5);
		DEEP_DARK_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.DARK_OAK_LOG)), 5);
		DEEP_DARK_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.DARK_OAK_SAPLING)), 5);
		DEEP_DARK_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.ECHO_SHARD)), 5);
		DEEP_DARK_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.GOLDEN_CARROT)), 5);
		DEEP_DARK_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.DEEPSLATE)), 5);
		ItemStack deepslateIronGrade = new ItemStack(Material.DEEPSLATE);
		ItemGradeUtils.setItemGrade(deepslateIronGrade, ItemGrade.IRON);
		DEEP_DARK_LOOT_TABLE.add(new SimpleLootTableEntry(deepslateIronGrade), 3);
		DEEP_DARK_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.OBSIDIAN)), 5);
		DEEP_DARK_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.SCULK)), 5);
		DEEP_DARK_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.BONE)), 5);
		DEEP_DARK_LOOT_TABLE.add(new SimpleLootTableEntry(new ItemStack(Material.GOLDEN_APPLE)), 3);
		DEEP_DARK_LOOT_TABLE.add(new SimpleLootTableEntry(CustomItem.MAZE_RUNNER_BOOTS.getItemStack()), 3);
	}
	
}
